{
 "title": "APC UPS (SNMP)",
 "description": "Displays monitoring data collected from APC uninterruptible power supplies via SNMP.",
 "tags": [
  "APC",
  "apcupsd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysUpTime{job=\"apcups\"}"
    },
    {
     "expr": "upsBasicBatteryLastReplaceDate{job=\"apcups\"}"
    },
    {
     "expr": "upsAdvTestCalibrationDate{job=\"apcups\"}"
    },
    {
     "expr": "upsAdvTestLastDiagnosticsDate{job=\"apcups\"}"
    },
    {
     "expr": "upsBasicOutputStatus{job=\"apcups\"}"
    },
    {
     "expr": "upsAdvTestDiagnosticsResults{job=\"apcups\"}"
    },
    {
     "expr": "upsAdvTestDiagnosticSchedule{job=\"apcups\"}"
    }
   ]
  },
  {
   "title": "UPS load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvOutputLoad" }
   ]
  },
  {
   "title": "Mains frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsAdvInputFrequency" }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvBatteryCapacity" }
   ]
  },
  {
   "title": "Time spent on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "upsBasicBatteryTimeOnBattery" }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvBatteryTemperature" }
   ]
  },
  {
   "title": "Estimated uptime on batteries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "upsAdvBatteryRunTimeRemaining / 100"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "upsAdvBatteryActualVoltage", "legendFormat": "actual" },
    { "expr": "upsAdvBatteryNominalVoltage", "legendFormat": "nominal" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "upsAdvBatteryTemperature", "legendFormat": "Battery Temperature" }
   ]
  },
  {
   "title": "Charge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "upsAdvBatteryCapacity", "legendFormat": "Battery Charge" }
   ]
  },
  { "title": "AC and load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "upsAdvInputLineVoltage", "legendFormat": "input" },
    { "expr": "upsAdvOutputVoltage", "legendFormat": "output" }
   ]
  },
  {
   "title": "Mains Frequency (HZ)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upsAdvInputFrequency", "legendFormat": "HZ" }
   ]
  },
  {
   "title": "Output load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "upsAdvOutputLoad" }
   ]
  }
 ]
}