{
 "title": "blackbox status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "targets",
    "query": "label_values(probe_success{}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Http Status code",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime [30d]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(probe_success{instance=~\"$targets\"}[$__range]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 0",
     "legendFormat": "RED"
    }
   ]
  },
  { "title": "$targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Http Status code",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime [30d]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(probe_success{instance=~\"$targets\"}[$__range]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 0",
     "legendFormat": "RED"
    }
   ]
  },
  { "title": "$targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Http Status code",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime [30d]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(probe_success{instance=~\"$targets\"}[$__range]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 0",
     "legendFormat": "RED"
    }
   ]
  },
  { "title": "$targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Http Status code",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime [30d]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(probe_success{instance=~\"$targets\"}[$__range]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 0",
     "legendFormat": "RED"
    }
   ]
  }
 ]
}