{
 "title": "emon-pub",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_use\"}"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_solar\"}"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_import\"} + ignoring(entity, friendly_name) (clamp_min(sensor_unit_w{entity=\"sensor.emoncms_solar\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_use\"}, 0) * - 1)"
    }
   ]
  },
  {
   "title": "Use Solar",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(delta(sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"}[$__range]) - ignoring (entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_import_kwh\"}[$__range])) / ignoring (entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"}[$__range])"
    }
   ]
  },
  {
   "title": "Solar Export",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((delta(sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"}[$__range]) - ignoring(entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_import_kwh\"}[$__range]) - ignoring(entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_solar_kwh\"}[$__range])) * - 1) / ignoring (entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_solar_kwh\"}[$__range])"
    }
   ]
  },
  {
   "title": "Use Grid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(sensor_unit_w{entity=\"sensor.emoncms_import_kwh\"}[$__range]) / ignoring(entity, friendly_name) delta(sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"}[$__range])"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_use\"}",
     "legendFormat": "Use"
    },
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_import\"} + ignoring(entity, friendly_name) (clamp_min(sensor_unit_w{entity=\"sensor.emoncms_solar\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_use\"}, 0) * - 1)",
     "legendFormat": "Grid"
    },
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_solar\"}",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "format": "kwatth",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"}"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_solar_kwh\"}"
    }
   ]
  },
  {
   "title": "Import",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_import_kwh\"}"
    }
   ]
  },
  {
   "title": "Export",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "expr": "(sensor_unit_w{entity=\"sensor.emoncms_use_kwh\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_import_kwh\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_solar_kwh\"}) * - 1"
    }
   ]
  },
  {
   "title": "Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sensor_unit_w{entity=\"sensor.emoncms_use\"}, 0)",
     "legendFormat": "Use"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sensor_unit_w{entity=\"sensor.emoncms_solar\"}, 0)",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Import",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_import\"}",
     "legendFormat": "Import"
    }
   ]
  },
  {
   "title": "Export",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sensor_unit_w{entity=\"sensor.emoncms_solar\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_use\"}, 0)",
     "legendFormat": "Export"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_use\"}"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 22 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_solar\"}"
    }
   ]
  },
  {
   "title": "Import",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 22 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sensor_unit_w{entity=\"sensor.emoncms_import\"}"
    }
   ]
  },
  {
   "title": "Export",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 22 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min(sensor_unit_w{entity=\"sensor.emoncms_solar\"} - ignoring(entity, friendly_name) sensor_unit_w{entity=\"sensor.emoncms_use\"}, 0)"
    }
   ]
  }
 ]
}