{
 "title": "emon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "emoncms_use" }
   ]
  },
  {
   "title": "Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "emoncms_solar" }
   ]
  },
  {
   "title": "Grid",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "emoncms_import" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "emoncms_import", "legendFormat": "Grid" },
    { "expr": "emoncms_solar", "legendFormat": "Generation" },
    { "expr": "emoncms_use", "legendFormat": "Consumption" }
   ]
  },
  {
   "title": "Consume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "clamp_min(emoncms_use, 0)", "legendFormat": "Consume" }
   ]
  },
  {
   "title": "Solar",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "clamp_min(emoncms_solar, 0)", "legendFormat": "Solar" }
   ]
  },
  {
   "title": "Import",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "clamp_min(emoncms_import, 0)", "legendFormat": "Import" }
   ]
  },
  {
   "title": "Export",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "abs(clamp_max(emoncms_import, 0))",
     "legendFormat": "Export"
    }
   ]
  }
 ]
}