{
 "title": "GivForecast",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Flows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=~\"sensor.givenergy.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.emoncms_solar\"}",
     "legendFormat": "Solar Actual"
    },
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.energy_forecast_solar\"}",
     "legendFormat": "Solar Forecast"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.givenergy_battery_charge\"}",
     "legendFormat": "SOC Actual"
    },
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.energy_forecast_soc\"}",
     "legendFormat": "SOC Forecast"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.givenergy_charge_target\"}",
     "legendFormat": "SOC Target"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.emoncms_use\"}",
     "legendFormat": "Consumption Acutal"
    },
    {
     "expr": "homeassistant_sensor_power_w{entity=~\"sensor.energy_forecast_consumption\"}",
     "legendFormat": "Consumption Forecast"
    }
   ]
  },
  {
   "title": "Module SOC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity=\"sensor.givenergy_invertor_temperature\"}",
     "legendFormat": "Inverter"
    },
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity=\"sensor.givenergy_battery_module_1_temperature\"}",
     "legendFormat": "Module 1"
    },
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity=\"sensor.givenergy_battery_module_2_temperature\"}",
     "legendFormat": "Module 2"
    }
   ]
  },
  {
   "title": "Module SOC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.givenergy_battery_module_1_soc\"}",
     "legendFormat": "Module 1"
    },
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.givenergy_battery_module_2_soc\"}",
     "legendFormat": "Module 2"
    }
   ]
  },
  {
   "title": "Module Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_ah{entity=\"sensor.givenergy_battery_module_1_capacity\"}",
     "legendFormat": "Module 1"
    },
    {
     "expr": "homeassistant_sensor_unit_ah{entity=\"sensor.givenergy_battery_module_2_capacity\"}",
     "legendFormat": "Module 2"
    }
   ]
  }
 ]
}