{
 "title": "HG612",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "identifier",
    "label": "identifier",
    "query": "label_values(dsl_status, identifier)"
   },
   { "name": "host", "label": "host", "query": "label_values(dsl_status, host)" }
  ]
 },
 "panels": [
  { "title": "DSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Line Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "-avg(dsl_up_current_rate{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host)",
     "legendFormat": "Up: {{host}}/{{identifier}}"
    },
    {
     "expr": "avg(dsl_down_current_rate{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host)",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "Attainable Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "-avg(dsl_up_max_rate{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host)",
     "legendFormat": "Up: {{host}}/{{identifier}}"
    },
    {
     "expr": "avg(dsl_down_max_rate{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host)",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "avg(dsl_up_snr{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "avg(dsl_down_snr{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "Attenuation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "avg(dsl_up_attenuation{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "avg(dsl_down_attenuation{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "avg(dsl_up_power{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "avg(dsl_down_power{identifier=~\"$identifier\",host=~\"$host\"}) by (identifier, host) /10",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "CRC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dsl_up_crc{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "sum(rate(dsl_down_crc{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "FEC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dsl_up_fec{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "sum(rate(dsl_down_fec{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  },
  {
   "title": "HEC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dsl_up_hec{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "UP: {{host}}/{{identifier}}"
    },
    {
     "expr": "sum(rate(dsl_down_hec{identifier=~\"$identifier\",host=~\"$host\"}[$interval])) by (identifier, host)",
     "legendFormat": "Down: {{host}}/{{identifier}}"
    }
   ]
  }
 ]
}