{
 "title": "kube pod resources",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Over",
   "type": "table",
   "description": "Over provisioned containers in regards to CPU",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\"}) by (namespace, pod, container) -\n    sum(label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"} [5m]),\n      \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n      \"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (namespace, pod, container)\n  ) by (namespace, pod, container)\n)"
    }
   ]
  },
  {
   "title": "CPU Under",
   "type": "table",
   "description": "Under provisioned containers in regards to CPU",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"} [5m]),\n      \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n      \"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (namespace, pod, container) -\n    sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\"}) by (namespace, pod, container)\n  ) by (namespace, pod, container)\n)"
    }
   ]
  },
  {
   "title": "Memory Over",
   "type": "table",
   "description": "Over provisioned containers in regards to Memory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\"}) by (namespace, pod, container) -\n    sum(label_replace(label_replace(container_memory_usage_bytes{namespace=~\"^$namespace$\"},\n      \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n      \"container\", \"$1\", \"container_name\", \"(.*)\")\n     ) by (namespace, pod, container)\n  ) by (namespace, pod, container)\n)"
    }
   ]
  },
  {
   "title": "Memory Under",
   "type": "table",
   "description": "Under provisioned containers in regards to Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(label_replace(label_replace(container_memory_usage_bytes{namespace=~\"^$namespace$\"},\n      \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n      \"container\", \"$1\", \"container_name\", \"(.*)\")\n     ) by (namespace, pod, container)\n  ) by (namespace, pod, container) -\n  sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\"}) by (namespace, pod, container)\n)"
    }
   ]
  }
 ]
}