{
 "title": "kube dns",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average RPS [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "rps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Average Response Time [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_sum[$interval]))/sum(rate(coredns_dns_request_duration_seconds_count[$interval]))"
    }
   ]
  },
  {
   "title": "Average Cache Hit Rate [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{}[$interval])) / (sum(rate(coredns_cache_misses_total{}[$interval])) + sum(rate(coredns_cache_hits_total{}[$interval])))"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RPS [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{}[$interval])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.999, sum(rate(coredns_dns_request_duration_seconds_bucket{}[$interval])) by (le))",
     "legendFormat": "99.9%"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(coredns_dns_request_duration_seconds_bucket{}[$interval])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(.90, sum(rate(coredns_dns_request_duration_seconds_bucket{}[$interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(.75, sum(rate(coredns_dns_request_duration_seconds_bucket{}[$interval])) by (le))",
     "legendFormat": "75% "
    }
   ]
  },
  {
   "title": "Upstream Response Time [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.999, sum(rate(coredns_forward_request_duration_seconds_bucket{}[$interval])) by (le, to))",
     "legendFormat": "99.9% {{to}}"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(coredns_forward_request_duration_seconds_bucket{}[$interval])) by (le, to))",
     "legendFormat": "99% {{to}}"
    },
    {
     "expr": "histogram_quantile(.90, sum(rate(coredns_forward_request_duration_seconds_bucket{}[$interval])) by (le, to))",
     "legendFormat": "90% {{to}}"
    },
    {
     "expr": "histogram_quantile(.75, sum(rate(coredns_forward_request_duration_seconds_bucket{}[$interval])) by (le, to))",
     "legendFormat": "75% {{to}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{}[$interval])) / (sum(rate(coredns_cache_misses_total{}[$interval])) + sum(rate(coredns_cache_hits_total{}[$interval])))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Response Codes Per  Second [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{}[$interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Upstream Response Codes Per  Second [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_response_rcode_count_total{}[$interval])) by (rcode, to)",
     "legendFormat": "{{rcode}} {{to}}"
    }
   ]
  },
  {
   "title": "Upstream Sockets Open [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_forward_sockets_open{}) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Panics Per Second [$interval avg]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_panic_count_total{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_name=~\"kube-dns\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_name=~\"kube-dns\" }",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{kubernetes_name=~\"kube-dns\"}) by (quantile, kubernetes_pod_name)",
     "legendFormat": "{{quantile}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_name=~\"kube-dns\"}",
     "legendFormat": "{{quantile}} {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}