{
 "title": "kube traefik",
 "description": "Kubernetes traefik metrics",
 "tags": [
  "system",
  "kubernetes",
  "traefik"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Traefik Deployments [req/s]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{name != \"\"}[5m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Service Traffic [req/s]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{service != \"https-proto\", service != \"http-redirect\", service != \"http\"}[5m])) by(backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Entrypoints [req/s]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{protocol =~ \"https-proto|http-redirect|http\",name != \"\"}[5m])) by(protocol,name)",
     "legendFormat": "{{name}}/{{protocol}}"
    }
   ]
  }
 ]
}