{
 "title": "MongoDB",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "mongodb",
    "label": "mongodb",
    "query": "label_values(mongodb_instance_uptime_seconds{kubernetes_namespace=\"$namespace\"}, kubernetes_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(mongodb_instance_uptime_seconds{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$mongodb\"},kubernetes_pod_name)"
   },
   {
    "name": "database",
    "query": "label_values(mongodb_mongod_top_count_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$mongodb\",kubernetes_pod_name=~\"$node\"},database)"
   },
   {
    "name": "collection",
    "query": "label_values(mongodb_mongod_top_count_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$mongodb\",kubernetes_pod_name=~\"$node\",database=~\"$database\"},collection)"
   },
   {
    "name": "op_type",
    "query": "label_values(mongodb_mongod_top_count_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$mongodb\",kubernetes_pod_name=~\"$node\",database=~\"$database\", collection=~\"$collection\"},type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(mongodb_instance_uptime_seconds{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_connections{state=\"available\", kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_connections{state=\"current\", kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])",
     "legendFormat": "{{type}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])",
     "legendFormat": "{{state}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Ops/Sec - $Interval avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_top_count_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\", database=~\"$database\", collection=~\"$collection\", type=~\"$op_type\"}[$Interval])) by (kubernetes_namespace, kubernetes_name, kubernetes_pod_name, database, collection, type) ",
     "legendFormat": " {{kubernetes_pod_name}}/{{database}}/{{collection}} ({{type}})"
    }
   ]
  },
  {
   "title": "Avg Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_top_time_seconds_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\", database=~\"$database\", collection=~\"$collection\", type=~\"$op_type\"}[$Interval])) by (kubernetes_namespace, kubernetes_name, kubernetes_pod_name, database, collection, type) / sum(rate(mongodb_mongod_top_count_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\", database=~\"$database\", collection=~\"$collection\", type=~\"$op_type\"}[$Interval])) by (kubernetes_namespace, kubernetes_name, kubernetes_pod_name, database, collection, type) ",
     "legendFormat": " {{kubernetes_pod_name}}/{{database}}/{{collection}} ({{type}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}",
     "legendFormat": "{{type}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])",
     "legendFormat": "{{state}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])",
     "legendFormat": "{{state}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Total Open Cursors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{kubernetes_namespace=\"$namespace\", state=\"scanned_objects\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])) by (kubernetes_pod_name)/sum(increase(mongodb_mongod_metrics_document_total{kubernetes_namespace=\"$namespace\", state=\"returned\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])) by (kubernetes_pod_name)",
     "legendFormat": "document ({{kubernetes_pod_name}})"
    },
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{kubernetes_namespace=\"$namespace\", state=\"scanned\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])) by (kubernetes_pod_name)/sum(increase(mongodb_mongod_metrics_document_total{kubernetes_namespace=\"$namespace\", state=\"returned\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])) by (kubernetes_pod_name)",
     "legendFormat": "index ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}[$Interval])",
     "legendFormat": "{{type}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_size_bytes{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}",
     "legendFormat": "{{type}} ({{kubernetes_pod_name}})"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_extra_info_heap_usage_bytes{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$mongodb\", kubernetes_pod_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}