{
 "title": "traefik",
 "description": "Simple dashboard for Traefik 2",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "protocol",
    "label": "Service:",
    "query": "label_values(traefik_service_requests_total, protocol)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "traefik", "label": "traefik", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "404 Error Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{app=~\"$traefik\",code=\"404\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "503 Error count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{app=~\"$traefik\",code=\"503\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{app=~\"$traefik\"}) / sum(traefik_entrypoint_requests_total{app=~\"$traefik\"}) * 1000"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{app=~\"$traefik\",protocol=~\"$protocol\"}) / sum(traefik_entrypoint_requests_total{app=~\"$traefik\",protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(traefik_service_requests_total{app=~\"$traefik\",protocol=~\"$protocol\"}[$interval])) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{app=~\"$traefik\"}[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{app=~\"$traefik\",code=\"404\",method=\"GET\",protocol=~\"$protocol\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app=~\"$traefik\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{app=~\"$traefik\",protocol=~\"http|https\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{app=~\"$traefik\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{app=~\"$traefik\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{app=~\"$traefik\",protocol=~\"$protocol\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}